import { randomUUID } from 'crypto';

const DEFAULT_ACCOUNT_PRODUCT_CODE = 'CHEQUE';
const DEFAULT_PRIMARY_BANK_ID = 'FNB';
const DEFAULT_PRIMARY_BRANCH_CODE = '250655';
const DEFAULT_SECONDARY_BANK_ID = 'ABSA';
const DEFAULT_SECONDARY_BRANCH_CODE = '632005';

export function uniqueId(prefix: string): string {
  return `${prefix}-${randomUUID().slice(0, 8).toUpperCase()}`;
}

// ---- Account factories ----

export function makeCreateAccountPayload() {
  return {
    productCode: DEFAULT_ACCOUNT_PRODUCT_CODE,
    customerId: uniqueId('CUST'),
    name: `Test Account ${uniqueId('ACC')}`,
    currency: 'ZAR',
  };
}

// ---- Customer factories ----

export function makeCreateCustomerPayload() {
  return {
    firstName: 'Test',
    lastName: `User-${uniqueId('LN')}`,
    email: `test-${uniqueId('EM').toLowerCase()}@example.com`,
    idNumber: `7001010001${Math.floor(Math.random() * 90 + 10)}`,
  };
}

// ---- Beneficiary factories ----

export function makeCreateBeneficiaryPayload() {
  return {
    name: `Beneficiary ${uniqueId('BEN')}`,
    bankAccountNumber: `12345${Math.floor(Math.random() * 100000)}`,
    bankId: DEFAULT_PRIMARY_BANK_ID,
    branchCode: DEFAULT_PRIMARY_BRANCH_CODE,
    reference: uniqueId('REF'),
  };
}

// ---- Customer message factories ----

export function makeCreateCustomerMessagePayload() {
  return {
    subject: `Test Subject ${uniqueId('SUBJ')}`,
    body: 'This is a test message body generated by the API test suite.',
  };
}

// ---- Transaction request factories ----

export function makeBeneficiaryTransactionRequestPayload() {
  return {
    amount: 100.00,
    currency: 'ZAR',
    beneficiaryId: uniqueId('BENID'),
    reference: uniqueId('REF'),
    description: 'Test beneficiary payment',
  };
}

export function makeFreeFormTransactionRequestPayload() {
  return {
    amount: 50.00,
    currency: 'ZAR',
    toAccountNumber: `4321${Math.floor(Math.random() * 1000000)}`,
    toBankId: DEFAULT_SECONDARY_BANK_ID,
    toBranchCode: DEFAULT_SECONDARY_BRANCH_CODE,
    reference: uniqueId('REF'),
    description: 'Test free form payment',
  };
}

export function makePublicAccountTransactionRequestPayload() {
  return {
    amount: 75.00,
    currency: 'ZAR',
    toAccountId: uniqueId('PUBACCT'),
    reference: uniqueId('REF'),
    description: 'Test public account payment',
  };
}

export function makeTransferToAccountTransactionRequestPayload() {
  return {
    amount: 200.00,
    currency: 'ZAR',
    toAccountId: uniqueId('ACCTID'),
    reference: uniqueId('REF'),
    description: 'Test internal transfer',
  };
}

// ---- FICA factories ----

export function makeIndividualFicaPayload() {
  return {
    customerId: uniqueId('CUST'),
    idNumber: `8001010001${Math.floor(Math.random() * 90 + 10)}`,
    firstName: 'Test',
    lastName: `FicaUser-${uniqueId('LN')}`,
    dateOfBirth: '1980-01-01',
    address: {
      line1: '1 Test Street',
      city: 'Johannesburg',
      postalCode: '2000',
      country: 'ZA',
    },
  };
}

export function makePatchFicaPayload() {
  return {
    status: 'APPROVED',
  };
}

// ---- User factories ----

export function makeCreateUserPayload() {
  const uid = uniqueId('USR').toLowerCase();
  return {
    username: uid,
    email: `${uid}@example.com`,
    firstName: 'Test',
    lastName: `User-${uniqueId('LN')}`,
  };
}

// ---- Entitlement factories ----

export function makeEntitlementPayload() {
  return {
    permission: 'ACCOUNT_VIEW',
    resourceId: uniqueId('RES'),
  };
}

// ---- Validate account factories ----

export function makeValidateAccountPayload() {
  return {
    accountNumber: `1234${Math.floor(Math.random() * 100000)}`,
    bankId: DEFAULT_PRIMARY_BANK_ID,
    branchCode: DEFAULT_PRIMARY_BRANCH_CODE,
  };
}

// ---- AVS verification factories ----

export function makeAvsRequestPayload() {
  return {
    accountNumber: `9876${Math.floor(Math.random() * 100000)}`,
    idNumber: `9001010001${Math.floor(Math.random() * 90 + 10)}`,
    name: 'Test Verification',
  };
}
